import express from 'express';
import { getDashboardStats, getDashboardCharts, getRecentActivity, getLocationOverview } from '../controllers/dashboardController.js';
import { authenticate } from '../middleware/auth.js';
const router = express.Router();
router.use(authenticate);
router.get('/stats', getDashboardStats);
router.get('/charts', getDashboardCharts);
router.get('/activity', getRecentActivity);
router.get('/locations', getLocationOverview);
export default router;
